server:
  port: 8080
  tomcat:
    connection-timeout: 20s
    keep-alive-timeout: 30000
  servlet:
    session:
      timeout: 30s

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Shiv@130998$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.apache.coyote.http11.Http11Processor: DEBUG
    org.springframework.web: DEBUG


